name: Matt Gauger
title: Matt Gauger
email: contact@mattgauger.com
description: > # this means to ignore newlines until "baseurl:"

# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          mattgauger.com
baseurl:        ""
url:            "http://mattgauger.com"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown
kramdown:
  input: GFM
highlighter: rouge
source: "source"
deploy: "gh-pages"
destination: "gh-pages"
permalink: "pretty"

# About
author:
  name:         Matt Gauger
  url:          http://mattgauger.com
  email:        contact@mattgauger.com

github_username: mathias
